### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by GemaLuo**
DC name: OliviaLuo
Thank you.
http://44.229.57.144:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your code will load many attractions which are not filtered by keyword if we do keyword search.

**Comment by GemaLuo** [comment]
Problem solved. Please review again. Thank you!
http://44.229.57.144:3000/

**Review by cwpeng — DISMISSED** [review]
OK. Done.

**Comment by GemaLuo** [comment]
I resloved the merger conflicts and it shows that user need to request a review again.  Could you help me to approve it again ? Thank you.

**Review by cwpeng — APPROVED** [review]
OK.

**Pull request merged**
