### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by GemaLuo**
OliviaLuo
**Correct **URLs**** 
http://44.229.57.144:3000/api/categories
http://44.229.57.144:3000/api/attractions?page=0
http://44.229.57.144:3000/api/attractions?page=1&keyword=北
http://44.229.57.144:3000/api/attraction/2

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Your live URLs are incorrect.

**Comment by GemaLuo** [comment]
OliviaLuo
http://44.229.57.144:3000/api/categories
http://44.229.57.144:3000/api/attractions?page=0
http://44.229.57.144:3000/api/attractions?page=1&keyword=北
http://44.229.57.144:3000/api/attraction/2

**Review by cwpeng — COMMENTED** [review]
Your live URLs are broken after some testings.

**Comment by GemaLuo** [comment]
I fixed the problem. Please review again, Thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Failed again. As a web server, we have to promise 99.5% available in a year, so, we have to find out source of problem and solve it, not just restart.

**Comment by GemaLuo** [comment]
problems solved below: 
1. connection pool exhausted(db.close())
2. add Exception, TypeError, ValueError
3. flatten 2D image data to 1D
4. longitude, latitude type(string to number)

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should use keyword to search category and name, not just name.

**Comment by GemaLuo** [comment]
景點分類：
http://44.229.57.144:3000/api/categories
景點頁數：
http://44.229.57.144:3000/api/attractions?page=1
http://44.229.57.144:3000/api/attractions?page=3
關鍵字：
1.（模糊）景點名稱：LOCATE
http://44.229.57.144:3000/api/attractions?page=0&keyword=關渡
http://44.229.57.144:3000/api/attractions?page=0&keyword=北投
2.（完全）景點分類：=
http://44.229.57.144:3000/api/attractions?page=0&keyword=藝文館所
http://44.229.57.144:3000/api/attractions?page=0&keyword=宗教信仰
景點ID：
http://44.229.57.144:3000/api/attraction/30
http://44.229.57.144:3000/api/attraction/6

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
